# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Water Protector Anti-Repression
email: info@antirepressioncrew.org
description: > # this means to ignore newlines until "baseurl:"
  As extraction becomes the norm and the government ramps up its repression against those who stand in resistance, this workshop holds valuable information for those who struggle for Indigenous sovereignty, earth liberation and a future without oppression.

  This website accompanies our two-hour workshop, which is open to all who have participated in the movement at Standing Rock; those who have supported the efforts on the ground from their homes and territories elsewhere; as well as all those who wish to continue fighting on the many frontlines that continue emerging across Turtle Island.

  The fight isn’t over at Standing Rock, as nearly 800 Water Protectors continue their battles in the courtrooms with some facing federal felony indictments that carry a potential of 15 years in federal prison. The grand jury convened against water protectors continues, as does the resistance to it. Strong movements and interdependent relationships make us resilient against attempts to shut down our struggle.

baseurl: "" # the subpath of your site, e.g. /blog
url: "antirepressioncrew.org" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
theme: blackdoc
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
